#!/bin/sh

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
docker buildx build \
	--platform linux/amd64,linux/arm64,linux/s390x,linux/arm/v7,linux/arm/v6 \
	--build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
	--build-arg SOURCE_COMMIT \
	--build-arg DOCKER_REPO \
	--progress plain --push \
	-f $DOCKERFILE_PATH -t $IMAGE_NAME .
