#!/bin/sh

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
# docker pull tonistiigi/binfmt:latest
# docker run --rm --privileged tonistiigi/binfmt:latest --install all
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
uname -a
docker version
docker info
docker buildx create \
	--name builder \
	--driver docker-container \
	--platform linux/amd64,linux/arm64,linux/s390x,linux/arm/v7,linux/arm/v6 \
	--use
docker buildx inspect --bootstrap
