#!/bin/sh

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
uname -a
apt update
apt upgrade
docker version
docker info
docker pull tonistiigi/binfmt:latest
docker run --privileged --rm tonistiigi/binfmt:latest --install arm64,arm
# docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create \
	--name builder \
	--driver docker-container \
	--platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
	--use
docker buildx inspect --bootstrap
